name: Release

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 */3 * *" # Every 3 days
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm
        run: 
          npm install -g npm@~11.10.0
          npm install -g npm@latest
      - name: Install & Enable Corepack
        run: npm install -g corepack && corepack enable
      - name: Install Dependencies
        run: pnpm install
      - run: mkdir ./data && git fetch origin && git --work-tree=./data checkout origin/gh-pages -- . && git reset
      - id: shouldContinue
        if: github.event_name != 'push'
        run: pnpx tsx src/checkNeedsPublish.ts
      - run: echo $OUTPUT
        if: github.event_name != 'push'
        env:
          OUTPUT: ${{ steps.shouldContinue.outputs.shouldContinue }}
      - run: pnpx zardoy-release npm
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: pnpx zardoy-release npm --auto-update
        if: github.event_name != 'push' && steps.shouldContinue.outputs.shouldContinue == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' || (github.event_name != 'push' && steps.shouldContinue.outputs.shouldContinue == 'true')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: data
          force_orphan: true
